export const siteConfig = {
  brandName: "STRONG4K",
  tagline: "Meilleur Abonnement IPTV 4K France Sans Coupure",
  description:
    "Découvrez le meilleur abonnement IPTV 4K Ultra HD en France sans coupure. Profitez de +22 000 chaînes en direct et VOD en qualité 4K 60FPS. Compatible Smart TV (Samsung, LG), Amazon Firestick, Android Box, IPTV Smarters Pro, Tivimate, Xtream Codes et M3U. Activation instantanée & Support VIP 7j/7.",
  seoKeywords: [
    "meilleur abonnement iptv france",
    "abonnement iptv 4k",
    "abonnement iptv pas cher",
    "iptv sans coupure",
    "fournisseur iptv france",
    "fournisseur iptv fiable france",
    "acheter abonnement iptv",
    "test iptv 24h gratuit",
    "iptv premium france 4k",
    "iptv france officiel",
    "french iptv",
    "france iptv",
    "pure iptv",
    "iron iptv",
    "atlas iptv",
    "atlas pro iptv",
    "smart iptv",
    "smartone iptv",
    "xtream iptv",
    "rg iptv",
    "xenon iptv",
    "agence iptv",
    "iptv az",
    "iptv hottest",
    "king iptv 4k",
    "king 365 tv 4k",
    "crystal iptv ott",
    "volka iptv pro",
    "gogo iptv 4k",
    "dino iptv ott",
    "trev iptv 4k",
    "orca iptv pro",
    "magnum iptv ott",
    "mega ott iptv 4k",
    "air tv iptv 4k",
    "neo tv pro 2",
    "qhdtv pro 4k",
    "dream tv pro iptv",
    "viper iptv 4k",
    "zaltv code iptv",
    "boitier iptv amazon",
    "boîtier iptv",
    "iptv smart tv samsung",
    "iptv smart tv lg",
    "iptv smart tv sony",
    "iptv smart tv hisense",
    "iptv smart tv tcl",
    "iptv smart tv philips",
    "iptv smart tv panasonic",
    "iptv amazon firestick",
    "amazon fire tv stick iptv",
    "amazon fire tv cube 4k",
    "iptv smarters pro france",
    "iptv smarters pro windows",
    "smarters player lite iptv",
    "tivimate iptv 4k",
    "tivimate premium iptv",
    "ibo player iptv",
    "ibo player pro abonnement",
    "bob player iptv 4k",
    "ott navigator iptv",
    "room iptv player",
    "smart stb iptv app",
    "stb emu pro iptv",
    "xciptv player 4k",
    "flix iptv france",
    "set iptv activation",
    "net iptv activation",
    "gse smart iptv pro",
    "nanomid player iptv",
    "televizo iptv player",
    "mytvonline 3 formuler",
    "iptv extreme pro 4k",
    "vu+ enigma 2 iptv",
    "serveur xtream codes iptv",
    "lien m3u iptv france",
    "code xtream iptv actif",
    "activation adresse mac mag",
    "iptv android tv box",
    "iptv apple tv 4k",
    "iptv formuler z11 pro max",
    "iptv formuler z10 pro",
    "iptv xiaomi mi box 4k",
    "iptv nvidia shield tv pro",
    "iptv mag 524 322",
    "iptv chromecast google tv",
    "iptv freebox pop ultra",
    "iptv livebox orange fibre",
    "iptv bbox bouygues telecom",
    "iptv sfr box 8",
    "iptv foot 4k france",
    "iptv ligue 1 champions league 4k",
    "iptv rmc sport bein sports dazn",
    "iptv canal plus foot 4k",
    "iptv formule 1 f1 direct",
    "iptv ufc rmc combat 4k",
    "iptv motogp direct 4k",
    "iptv chaines francaises 4k",
    "iptv chaines arabes nilesat",
    "iptv chaines maghreb 4k",
    "iptv chaines espagnoles movistar",
    "iptv chaines italiennes sky",
    "iptv chaines portugaises meo",
    "iptv chaines uk sky sports",
    "iptv chaines usa nbc espn",
    "iptv chaines africaines canal+",
    "iptv vod films series 4k",
    "iptv netflix prime series",
    "iptv disney hbo max direct",
    "iptv stable sans freeze",
    "iptv hevc 60fps",
    "iptv anti buffering",
    "iptv paris 4k",
    "iptv lyon 4k",
    "iptv marseille 4k",
    "iptv toulouse 4k",
    "iptv nice bordeaux lille 4k",
    "iptv belgique 4k",
    "iptv suisse romande 4k",
    "iptv canada quebec 4k",
    "iptv luxembourg 4k",
    "abonnement iptv 12 mois",
    "iptv abonnement 12 mois",
    "iptv abonnement france",
    "abonnement iptv 6 mois",
    "abonnement iptv 1 mois",
  ],
  domain: process.env.NEXT_PUBLIC_SITE_URL || "https://www.strong4k.us",
  language: "fr-FR",
  supportEmail: "zprotv25@gmail.com",
  supportPhone: "+33 7 56 90 12 34",
  whatsAppNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "+212779395271",
  company: {
    name: "STRONG4K MEDIA SAS",
    address: "128 Rue La Boétie, 75008 Paris, France",
    registration: "RCS Paris B 918 273 645 | SIRET 91827364500012",
    vatNumber: "FR 82 918273645",
    capital: "10 000 €",
    publicationDirector: "Direction STRONG4K",
    host: "Vercel Inc. | 440 N Barranca Ave #4133, Covina, CA 91723, USA",
  },
  navLinks: [
    { label: "Abonnements", href: "/#abonnements" },
    { label: "Blog", href: "/blog" },
    { label: "Panel", href: "/panel" },
    { label: "Contact", href: "/contact" },
  ],
  footerLinks: {
    navigation: [
      { label: "Nos Offres", href: "/#abonnements" },
      { label: "Panel Reseller", href: "/panel" },
      { label: "Guides d'Installation", href: "/installation" },
      { label: "Foire Aux Questions", href: "/faq" },
    ],
    company: [
      { label: "À propos", href: "/a-propos" },
      { label: "Blog & Actualités", href: "/blog" },
      { label: "Nous Contacter", href: "/contact" },
    ],
    legal: [
      { label: "Conditions Générales de Vente", href: "/conditions-generales" },
      { label: "Politique de Confidentialité", href: "/politique-de-confidentialite" },
      { label: "Politique de Remboursement", href: "/politique-de-remboursement" },
    ],
  },
};

export function getWhatsAppUrl(planName?: string): string {
  const cleanNumber = siteConfig.whatsAppNumber.replace(/[^0-9]/g, "");
  const text = planName
    ? `Bonjour, je souhaite commander l'offre STRONG4K ${planName}. Merci de me donner les instructions pour finaliser la commande.`
    : "Bonjour, je souhaite commander un abonnement STRONG4K.";
  return `https://wa.me/${cleanNumber}?text=${encodeURIComponent(text)}`;
}
