export const siteConfig = {
  brandName: "STRONG4K",
  tagline: "Meilleur Abonnement IPTV 4K France Sans Coupure",
  description:
    "Découvrez le meilleur abonnement IPTV 4K Ultra HD en France sans coupure. Profitez de +22 000 chaînes en direct et VOD en qualité 4K 60FPS. Compatible Smart TV (Samsung, LG), Amazon Firestick, Android Box, IPTV Smarters Pro, Tivimate, Xtream Codes et M3U. Activation instantanée & Support VIP 7j/7.",
  seoKeywords: [
    "meilleur abonnement iptv france",
    "abonnement iptv france sans coupure",
    "fournisseur iptv france",
    "fournisseur iptv fiable france",
    "acheter abonnement iptv france",
    "acheter iptv france cb",
    "abonnement iptv officiel france",
    "abonnement iptv legal france",
    "test iptv 24h gratuit france",
    "test iptv gratuit 24 heures",
    "iptv premium france 4k",
    "iptv france 4k ultra hd",
    "iptv france sans freeze",
    "iptv france anti coupure",
    "iptv france avis forum",
    "iptv france paiement securise cb",
    "iptv france reception instantanee",
    "iptv france support francophone 7j/7",
    "iptv pas cher france",
    "abonnement iptv pas cher 12 mois",
    "code iptv france",
    "fournisseur iptv premium garanti",
    "french iptv",
    "france iptv",
    "pure iptv",
    "iron iptv",
    "atlas iptv",
    "atlas pro iptv",
    "smart iptv",
    "smartone iptv",
    "xtream iptv",
    "rg iptv",
    "xenon iptv",
    "agence iptv",
    "iptv az",
    "iptv hottest",
    "king iptv 4k",
    "king 365 tv 4k",
    "crystal iptv ott",
    "volka iptv pro",
    "gogo iptv 4k",
    "dino iptv ott",
    "trev iptv 4k",
    "orca iptv pro",
    "magnum iptv ott",
    "mega ott iptv 4k",
    "air tv iptv 4k",
    "neo tv pro 2",
    "qhdtv pro 4k",
    "dream tv pro iptv",
    "viper iptv 4k",
    "zaltv code iptv",
    "boitier iptv amazon",
    "boîtier iptv france",
    "meilleur boitier iptv 4k",
    "iptv smart tv samsung france",
    "iptv smart tv lg webos france",
    "iptv smart tv sony bravia",
    "iptv smart tv hisense vidaa",
    "iptv smart tv tcl android",
    "iptv smart tv philips saphi",
    "iptv smart tv panasonic",
    "iptv amazon firestick france",
    "amazon fire tv stick iptv",
    "amazon fire tv cube 4k",
    "iptv smarters pro france",
    "iptv smarters pro windows",
    "smarters player lite iptv france",
    "tivimate iptv 4k france",
    "tivimate premium iptv",
    "tivimate code activation france",
    "ibo player iptv france",
    "ibo player pro abonnement",
    "ibo player code activation france",
    "bob player iptv 4k",
    "ott navigator iptv",
    "room iptv player",
    "smart stb iptv app",
    "stb emu pro iptv",
    "xciptv player 4k",
    "flix iptv france",
    "set iptv activation france",
    "net iptv activation france",
    "gse smart iptv pro",
    "nanomid player iptv",
    "televizo iptv player",
    "mytvonline 3 formuler france",
    "iptv extreme pro 4k",
    "vu+ enigma 2 iptv",
    "serveur xtream codes iptv france",
    "lien m3u iptv france",
    "code xtream iptv actif",
    "activation adresse mac mag france",
    "iptv android tv box france",
    "iptv apple tv 4k france",
    "iptv formuler z11 pro max",
    "iptv formuler z10 pro",
    "iptv xiaomi mi box 4k",
    "iptv xiaomi tv box s 2nd gen",
    "iptv nvidia shield tv pro france",
    "iptv mag 524 322",
    "iptv chromecast google tv",
    "iptv freebox pop ultra revolution",
    "iptv livebox orange fibre 6 7",
    "iptv bbox bouygues must ultym",
    "iptv sfr box 7 8 fibre",
    "iptv sosh fibre",
    "iptv red by sfr fibre",
    "iptv foot france 4k",
    "iptv ligue 1 mcdonalds 4k",
    "iptv ligue 2 bkt direct",
    "iptv coupe de france foot",
    "iptv champions league uefa 4k",
    "iptv dazn ligue 1 france",
    "iptv dazn france pas cher",
    "pass ligue 1 iptv france",
    "iptv canal plus foot 4k france",
    "iptv canal plus sport 360",
    "iptv bein sports france 1 2 3",
    "iptv rmc sport 1 2 uhd france",
    "iptv eurosport france 4k",
    "iptv formule 1 f1 canal+ 4k",
    "iptv motogp france direct 4k",
    "iptv top 14 rugby france 4k",
    "iptv roland garros 4k france",
    "iptv tour de france cyclisme 4k",
    "iptv ufc paris rmc combat 4k",
    "iptv chaines francaises 4k hevc",
    "iptv tnt france tf1 m6 france 2 3",
    "iptv bouquet canal+ france complet",
    "iptv bouquet cine+ ocs france",
    "iptv chaines arabes nilesat france",
    "iptv chaines maghreb maroc algerie tunisie",
    "iptv chaines marocaines france 2m al aoula",
    "iptv chaines algeriennes france entv",
    "iptv chaines tunisiennes france",
    "iptv chaines espagnoles movistar",
    "iptv chaines italiennes sky italia",
    "iptv chaines portugaises meo nos",
    "iptv chaines uk sky sports bt",
    "iptv chaines usa nbc espn",
    "iptv chaines africaines canal+ afrique",
    "iptv chaines turques france",
    "iptv vod films series francais 4k",
    "iptv netflix prime video series",
    "iptv disney plus hbo max direct",
    "iptv stable sans freeze france",
    "iptv hevc 60fps france",
    "iptv anti buffering france",
    "iptv paris 75",
    "iptv ile de france 4k",
    "iptv hauts de seine 92",
    "iptv seine saint denis 93",
    "iptv val de marne 94",
    "iptv yvelines 78",
    "iptv essonne 91",
    "iptv seine et marne 77",
    "iptv val d oise 95",
    "iptv lyon rhone alpes 69",
    "iptv marseille paca 13",
    "iptv toulouse occitanie 31",
    "iptv nice cote d azur 06",
    "iptv bordeaux aquitaine 33",
    "iptv lille hauts de france 59",
    "iptv strasbourg grand est 67",
    "iptv nantes pays de la loire 44",
    "iptv rennes bretagne 35",
    "iptv montpellier herault 34",
    "iptv toulon var 83",
    "iptv grenoble isere 38",
    "iptv dijon bourgogne 21",
    "iptv angers maine et loire 49",
    "iptv nimes gard 30",
    "iptv villeurbanne 69",
    "iptv saint etienne loire 42",
    "iptv le havre seine maritime 76",
    "iptv reims marne 51",
    "iptv clermont ferrand 63",
    "iptv le mans sarthe 72",
    "iptv aix en provence 13",
    "iptv brest finistere 29",
    "iptv tours indre et loire 37",
    "iptv amiens somme 80",
    "iptv limoges haute vienne 87",
    "iptv annecy haute savoie 74",
    "iptv perpignan pyrenees orientales 66",
    "iptv metz moselle 57",
    "iptv besancon doubs 25",
    "iptv orleans loiret 45",
    "iptv rouen seine maritime 76",
    "iptv mulhouse haut rhin 68",
    "iptv caen calvados 14",
    "iptv nancy meurthe et moselle 54",
    "iptv avignon vaucluse 84",
    "iptv poitiers vienne 86",
    "iptv la rochelle charente maritime 17",
    "iptv pau pyrenees atlantiques 64",
    "iptv chambery savoie 73",
    "iptv valence drome 26",
    "iptv lorient morbihan 56",
    "iptv troyes aube 10",
    "iptv ajaccio corse du sud 2a",
    "iptv bastia haute corse 2b",
    "iptv dom tom guadeloupe martinique reunion",
    "iptv guadeloupe pointe a pitre 971",
    "iptv martinique fort de france 972",
    "iptv la reunion saint denis 974",
    "iptv guyane cayenne 973",
    "iptv mayotte mamoudzou 976",
    "iptv nouvelle caledonie noumea",
    "iptv polynesie tahiti",
    "abonnement iptv 12 mois",
    "iptv abonnement 12 mois france",
    "iptv abonnement france 4k",
    "abonnement iptv 6 mois france",
    "abonnement iptv 1 mois sans engagement",
    "fournisseur iptv serveur prive france",
    "iptv france paiement cb 3d secure",
    "iptv france support technique 7j 7",
    "iptv france activation 5 minutes",
    "iptv france multi ecrans famille",
    "iptv france replay 7 jours",
    "iptv france guide programme epg",
  ],
  domain: process.env.NEXT_PUBLIC_SITE_URL || "https://www.strong4k.us",
  language: "fr-FR",
  supportEmail: "zprotv25@gmail.com",
  supportPhone: "+33 7 56 90 12 34",
  whatsAppNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || "+212779395271",
  company: {
    name: "STRONG4K MEDIA SAS",
    address: "128 Rue La Boétie, 75008 Paris, France",
    registration: "RCS Paris B 918 273 645 | SIRET 91827364500012",
    vatNumber: "FR 82 918273645",
    capital: "10 000 €",
    publicationDirector: "Direction STRONG4K",
    host: "Vercel Inc. | 440 N Barranca Ave #4133, Covina, CA 91723, USA",
  },
  navLinks: [
    { label: "Abonnements", href: "/#abonnements" },
    { label: "Blog", href: "/blog" },
    { label: "Panel", href: "/panel" },
    { label: "Contact", href: "/contact" },
  ],
  footerLinks: {
    navigation: [
      { label: "Nos Offres", href: "/#abonnements" },
      { label: "Panel Reseller", href: "/panel" },
      { label: "Guides d'Installation", href: "/installation" },
      { label: "Foire Aux Questions", href: "/faq" },
    ],
    company: [
      { label: "À propos", href: "/a-propos" },
      { label: "Blog & Actualités", href: "/blog" },
      { label: "Nous Contacter", href: "/contact" },
    ],
    legal: [
      { label: "Conditions Générales de Vente", href: "/conditions-generales" },
      { label: "Politique de Confidentialité", href: "/politique-de-confidentialite" },
      { label: "Politique de Remboursement", href: "/politique-de-remboursement" },
    ],
  },
};

export function getWhatsAppUrl(planName?: string): string {
  const cleanNumber = siteConfig.whatsAppNumber.replace(/[^0-9]/g, "");
  const text = planName
    ? `Bonjour, je souhaite commander l'offre STRONG4K ${planName}. Merci de me donner les instructions pour finaliser la commande.`
    : "Bonjour, je souhaite commander un abonnement STRONG4K.";
  return `https://wa.me/${cleanNumber}?text=${encodeURIComponent(text)}`;
}
